# Generated by Django 3.0.7 on 2020-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201009_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SH', 'Shirts'), ('SW', 'Sport Wears'), ('OW', 'Outwears')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
