# Generated by Django 3.0.7 on 2020-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description. alskdalkfjsdkfjglsdnvgsdkfbg.'),
            preserve_default=False,
        ),
    ]
