# Generated by Django 3.0.7 on 2021-01-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210108_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
